[package]
name = "managers_bindings"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"
test = false

[dependencies]
systypes = { path = "../../../../uapi/include/uapi/types" }

[build-dependencies]
bindgen = "0.69.1"
systypes = { path = "../../../../uapi/include/uapi/types" }
uapi = { path = "../../../../uapi/include/uapi" }
