[package]
name = "uapi"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
systypes = { path = "../systypes" }

[dev-dependencies]
uapi = { path = '.', features = ['std'] }

[features]
default = []
std = []
