[package]
name = "uapi"
version = "0.1.0"
edition = "2021"
license = "Apache 2.0"

[lib]
path = "lib.rs"

[dependencies]

[dev-dependencies]
uapi = { path = '.', features = ['std'] }

[features]
default = []
std = []
