[package]
name = "capabilities"
version = "0.1.0"
edition = "2021"

[lib]
path = "capability.rs"

[features]
cbindgen = []

[dependencies]
bitflags = "2.4.0"

[build-dependencies]
cbindgen = "0.26.0"
