# SPDX-FileCopyrightText: 2026 H2Lab Development Team
# SPDX-License-Identifier: Apache-2.0

[tox]
envlist = py,mypy,build
isolated_build = true

[testenv]
deps =
    pytest>=8
    grpcio>=1.80
    protobuf>=6.31
commands =
    pytest

[testenv:mypy]
deps =
    mypy>=1.10
    types-grpcio
    types-protobuf
commands =
    mypy src

[testenv:build]
deps =
    build>=1.2
commands =
    python -m build --sdist --wheel
