[package]
name = "uapi"
version = "0.1.0"
edition = "2021"

[lib]
path = "../../src/lib.rs"

[dependencies]
systypes = { path = "types" }

[dev-dependencies]
sysgate = { path = "../../../kernel/src/syscalls", features = ['mock'] }
uapi = { path = '.', features = ['std'] }

[features]
default = []
std = []
