[package]
name = "uapi"
version = "0.1.0"
edition = "2021"

[lib]
path = "../../src/lib.rs"

[dependencies]
systypes = { path = "types" }
handles = { path = "handles" }

[build-dependencies]
systypes = { path = "types" } # we need systypes to produce some C headers beforehand
handles = { path = "handles" }
cbindgen = "0.26.0"

[dev-dependencies]
sysgate = { path = "../../../kernel/src/syscalls", features = ['mock'] }
uapi = { path = '.', features = ['std'] }

[features]
default = []
std = []
