name: Sentry kernel build

on:
  push:
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# using /home/build as home, as buildbot is using user build. Cache is still in /cache
# This allows the usage of automated ssh key installation step

jobs:
  forge_matrix:
    runs-on: self-hosted
    container:
      image: python:3.9.14-alpine3.16
    steps:
      - id: set_matrix
        shell: python
        run: |
          import os
          if "${{ github.event_name }}" == "pull_request":
            operating_system = [ 'mesonbuild/fedora:latest', 'mesonbuild/ubuntu-rolling', 'mesonbuild/arch:latest', 'mesonbuild/opensuse:latest' ]
            toolchain = [ 'gcc|12.3.Rel1', 'gcc|11.2-2022.02', 'gcc|10.3-2021.07' ]
          else:
            operating_system = [ 'mesonbuild/ubuntu-rolling' ]
            toolchain = [ 'gcc|12.3.Rel1' ]
          with open(os.environ['GITHUB_OUTPUT'], 'w') as gh_out:
            gh_out.write(f"operating_system={operating_system}\n")
            gh_out.write(f"toolchain={toolchain}\n")
    outputs:
      operating_system: ${{ steps.set_matrix.outputs.operating_system }}
      toolchain: ${{ steps.set_matrix.outputs.toolchain }}


  build:
    needs: [ forge_matrix ]
    strategy:
      matrix:
        operating_system: ${{ fromJSON(needs.forge_matrix.outputs.operating_system) }}
        toolchain: ${{ fromJSON(needs.forge_matrix.outputs.toolchain) }}
        exclude:
        - operating_system: 'mesonbuild/fedora:latest'
          toolchain: 'gcc|10.3-2021.07'
    name: build
    defaults:
      run:
        shell: bash
    runs-on: self-hosted
    container:
      image: ${{ matrix.operating_system }}
    steps:
      - name: Setup git
        uses: embedded-devops/action-setup-git@main
        with:
          ssh_key: ${{ secrets.GHE_SSH_KEY }}
          ssh_known_hosts: ${{ secrets.GHE_HOST_KEY }}
      - name: Setup Meson
        uses: embedded-devops/action-setup-meson@main
        with:
          token: ${{ secrets.GHE_CI_TOKEN }}
          crossfiles_git: 'outpost/meson-cross-files'
          crossfiles_ref: 'main'
      - name: Split compiler reference
        id: split
        shell: bash
        run: |
          input_toolchain="${{matrix.toolchain}}"
          toolchain_compiler=${input_toolchain%%|*}
          toolchain_version=${input_toolchain##*|}
          echo "compiler=$toolchain_compiler" >> $GITHUB_ENV
          echo "compiler_version=$toolchain_version" >> $GITHUB_ENV
      - name: Setup compiler
        uses: embedded-devops/action-setup-compiler@main
        with:
          compiler: ${{ env.compiler }}
          triple: arm-none-eabi
          ref: ${{ env.compiler_version }}
      - name: Set pypi credentials
        uses: embedded-devops/action-pypi@main
        with:
          pypi_server_url: 'https://nexus.orange.ledgerlabs.net/repository/kulos-pypi'
          pypi_server_need_authentication: true
          pypi_server_login: ${{ secrets.KULOS_NEXUS_CI_RO_USER }}
          pypi_server_password: ${{ secrets.KULOS_NEXUS_CI_RO_PASSWORD }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: deploy local deps
        run: |
          pip install -r requirements.txt
      - name: install pkg
        uses: embedded-devops/action-install-pkg@v1.0
        with:
          package: 'dtc,device-tree-compiler'
      - name: Meson Build
        uses: embedded-devops/action-meson@main
        with:
          cross_files: ${{ format('{0}/{1}', env.MESON_CROSS_FILES, 'arm-none-eabi-gcc.ini') }}
          actions: '["prefetch", "setup", "compile"]'
          options: '-Dkconfig:config=configs/stm32f429i_disc1_defconfig'
      - name: Meson postcheck
        if: failure()
        run: |
          cat builddir/meson-logs/meson-log.txt

  test:
    needs: [ build ]
    defaults:
      run:
        shell: bash
    runs-on: self-hosted
    container:
      image: 'mesonbuild/ubuntu-rolling'
    steps:
      - name: Setup git
        uses: embedded-devops/action-setup-git@main
        with:
          ssh_key: ${{ secrets.GHE_SSH_KEY }}
          ssh_known_hosts: ${{ secrets.GHE_HOST_KEY }}
      - name: Setup Meson
        uses: embedded-devops/action-setup-meson@main
        with:
          token: ${{ secrets.GHE_CI_TOKEN }}
          crossfiles_git: 'outpost/meson-cross-files'
          crossfiles_ref: 'main'
      - name: Setup compiler
        uses: embedded-devops/action-setup-compiler@main
        with:
          compiler: gcc
          triple: arm-none-eabi
          ref: '12.3.Rel1'
      - name: Set pypi credentials
        uses: embedded-devops/action-pypi@main
        with:
          pypi_server_url: 'https://nexus.orange.ledgerlabs.net/repository/kulos-pypi'
          pypi_server_need_authentication: true
          pypi_server_login: ${{ secrets.NEXUS_CI_RO_USER }}
          pypi_server_password: ${{ secrets.NEXUS_CI_RO_PASSWORD }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: deploy local deps
        run: |
          pip install -r requirements.txt
      - name: install pkg
        uses: embedded-devops/action-install-pkg@v1.0
        with:
          package: 'dtc,device-tree-compiler'
      - name: Meson Build
        uses: embedded-devops/action-meson@main
        with:
          cross_files: ${{ format('{0}/{1}', env.MESON_CROSS_FILES, 'arm-none-eabi-gcc.ini') }}
          actions: '["prefetch", "setup", "test"]'
          options: '-Dkconfig:config=configs/stm32f429i_disc1_defconfig -Dwith_tests=true -Db_coverage=false -Doptimization=0'
      - name: Meson postcheck
        if: failure()
        run: |
          cat builddir/meson-logs/meson-log.txt
          cat builddir/meson-logs/testlog.txt
