name: Sentry kernel build on MacOS

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# using /home/build as home, as buildbot is using user build. Cache is still in /cache
# This allows the usage of automated ssh key installation step

jobs:
  build_u5_macosX:
    defaults:
      run:
        shell: bash
    runs-on: macos-latest
    steps:
      - name: Clone cross-files
        uses: actions/checkout@v4
        with:
          ref:  'using-local-dirs'
          repository: 'outpost-os/meson-cross-files'
          path: crossfiles
      - name: Deploy cross-files
        run: |
          mkdir -p $HOME/.local/share/meson/cross
          cp -a $GITHUB_WORKSPACE/crossfiles/*.ini $HOME/.local/share/meson/cross
          echo "MESON_CROSS_FILES=$HOME/.local/share/meson/cross" >> $GITHUB_ENV
        shell: bash
      - name: install prerequisites pkg
        run: |
          brew install dtc libssh2 curl srecord rustup
        shell: bash
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          targets: thumbv7m-none-eabi,thumbv7em-none-eabi,thumbv7em-none-eabihf
          components: clippy,rustfmt
      - name: Setup C toolchain
        uses: outpost-os/action-setup-compiler@use-local-dir
        with:
          compiler: gcc
          triple: arm-none-eabi
          ref: 13.2.Rel1
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          set-safe-directory: true
      - name: set safe dir for dunami (to be removed)
        run: |
          git config --global --add safe.directory '*'
        shell: bash
      - name: deploy local deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          echo '$HOME/Library/Python/3.12/bin' >> $GITHUB_PATH
      - name: defconfig
        run: |
          defconfig configs/nucleo_u5a5_autotest_defconfig
      - name: Meson Build
        uses: outpost-os/action-meson@support-custom-pip-bin-name
        with:
          cross_files: ${{ format('{0}/{1}', env.MESON_CROSS_FILES, 'darwin-arm-none-eabi-gcc.ini') }}
          actions: '["prefetch", "setup", "compile"]'
          options: '-Dconfig=.config -Ddts=dts/examples/nucleo_u5a5_autotest.dts -Ddts-include-dirs=dts'
          pip: 'pip'
      - name: Meson postcheck
        if: failure()
        run: |
          cat builddir/meson-logs/meson-log.txt
