name: Sentry kernel proof

on:
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  run_framac:
    defaults:
      run:
        shell: bash
    runs-on: self-hosted
    container:
      image: docker-kulos-nexus.orange.ledgerlabs.net/framac-27:latest
      credentials:
        username: ${{ secrets.NEXUS_CI_RO_USER }}
        password: ${{ secrets.NEXUS_CI_RO_PASSWORD }}

    steps:
      - name: Clear GITHUB_HOME at job start
        shell: bash
        run: |
          find $HOME -mindepth 1 -maxdepth 1 -not -name '.' -exec rm -rf {} \;
      - name: Setup git
        uses: embedded-devops/action-setup-git@main
        with:
          ssh_key: ${{ secrets.GHE_SSH_KEY }}
          ssh_known_hosts: ${{ secrets.GHE_HOST_KEY }}
      - name: Setup Meson
        uses: embedded-devops/action-setup-meson@main
        with:
          token: ${{ secrets.GHE_CI_TOKEN }}
          crossfiles_git: 'outpost/meson-cross-files'
          crossfiles_ref: 'main'
      - name: Set pypi credentials
        uses: embedded-devops/action-pypi@main
        with:
          pypi_server_url: 'https://nexus.orange.ledgerlabs.net/repository/kulos-pypi'
          pypi_server_need_authentication: true
          pypi_server_login: ${{ secrets.NEXUS_CI_RO_USER }}
          pypi_server_password: ${{ secrets.NEXUS_CI_RO_PASSWORD }}
      - name: install prerequisites pkg
        uses: embedded-devops/action-install-pkg@v2.0
        with:
          packages: 'dtc|device-tree-compiler,curl,lld'
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          targets: thumbv7m-none-eabi,thumbv7em-none-eabi,thumbv7em-none-eabihf
          components: clippy,rustfmt
      - name: Install (c)bindgen
        run: |
          cargo install cbindgen bindgen-cli --locked
      - name: Setup C toolchain
        uses: embedded-devops/action-setup-compiler@main
        with:
          compiler: gcc
          triple: arm-none-eabi
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Install local deps
        run: |
          pip3 install -r requirements.txt
      - name: Meson Build
        uses: embedded-devops/action-meson@main
        with:
          cross_files: ${{ format('{0}/{1}', env.MESON_CROSS_FILES, 'arm-none-eabi-gcc.ini') }}
          actions: '["prefetch", "setup"]'
          options: '-Dkconfig:config=configs/stm32f429i_disc1_defconfig -Dwith_proof=true'
      - name: build libsentry
        run: |
          cd builddir && ninja kernel/src/libsentry.a
      - name: run framaC
        run: |
          why3 config detect
          frama-c -wp-detect
          cd builddir && meson test --suite proof
      - name: Archive proof artifacts
        uses: actions/upload-artifact@v3
        with:
          name: framac-eva-results
          path: |
            builddir/proof/*.*
      - name: Meson postcheck
        if: failure()
        run: |
          cat builddir/meson-logs/meson-log.txt
          cat builddir/meson-logs/testlog.txt
