# SPDX-FileCopyrightText: 2024 Ledger SAS
#
# SPDX-License-Identifier: Apache-2.0

name: Generate sdist tarball

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# using /home/build as home, as buildbot is using user build. Cache is still in /cache
# This allows the usage of automated ssh key installation step

jobs:
  sdist:
    environment: publish
    permissions:
      id-token: write
      contents: read
      attestations: write
    name: sdist
    defaults:
      run:
        shell: bash
    runs-on: outpost-os-shared-small
    container:
      image: mesonbuild/ubuntu-rolling
    steps:
      - name: XXX git permission quirk XXX
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          set-safe-directory: true
      - name: Clone cross-files
        uses: actions/checkout@v4
        with:
          ref:  'main'
          repository: 'outpost-os/meson-cross-files'
          path: crossfiles
      - name: Deploy cross-files
        run: |
          mkdir -p $HOME/.local/share/meson/cross
          cp -a $GITHUB_WORKSPACE/crossfiles/*.ini $HOME/.local/share/meson/cross
          echo "MESON_CROSS_FILES=$HOME/.local/share/meson/cross" >> $GITHUB_ENV
        shell: bash
      - name: install prerequisites pkg
        uses: outpost-os/action-install-pkg@v1
        with:
          packages: 'dtc|device-tree-compiler,libssh2-1|libssh2,curl,lld,srecord'
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          targets: thumbv7m-none-eabi,thumbv7em-none-eabi,thumbv7em-none-eabihf
          components: clippy,rustfmt
      - name: Setup C toolchain
        uses: outpost-os/action-setup-compiler@v1
        with:
          compiler: gcc
          triple: arm-none-eabi
          ref: 13.2.Rel1
          workspace: $GITHUB_WORKSPACE
      - name: deploy local deps
        run: |
          pip install -r requirements.txt
      - name: defconfig
        run: |
          defconfig configs/nucleo_u5a5_autotest_defconfig
      - name: Meson Build
        uses: outpost-os/action-meson@v1
        with:
          cross_files: ${{ format('{0}/{1}', env.MESON_CROSS_FILES, 'arm-none-eabi-gcc.ini') }}
          actions: '["prefetch", "setup"]'
          options: '-Dconfig=.config -Ddts=dts/examples/nucleo_u5a5_autotest.dts -Ddts-include-dirs=dts'
      - name: Meson postcheck
        if: failure()
        run: |
          cat builddir/meson-logs/meson-log.txt
      - name: Meson dist
        run: |
          meson dist -C builddir --no-tests --include-subprojects
      - name: Login to JFrog Ledger
        uses: LedgerHQ/actions-security/actions/jfrog-login@actions/jfrog-login-1
      - name: upload package
        run: jf rt u --build-name=sentry-kernel-sdist-dev --build-number=1 --module=sentry-kernel 'builddir/meson-dist/*.*' ${{ secrets.JFROG_REPO_SDIST }}

