name: Sentry UAPI build

on:
  push:
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# using /home/build as home, as buildbot is using user build. Cache is still in /cache
# This allows the usage of automated ssh key installation step

jobs:
  buildncheck:
    defaults:
      run:
        shell: bash
    runs-on: self-hosted
    container:
      image: rust:latest
    steps:
      - name: Clear GITHUB_HOME at job start
        shell: bash
        run: |
          find $HOME -mindepth 1 -maxdepth 1 -not -name '.' -exec rm -rf {} \;
      - name: Add libclang for bindgen
        shell: bash
        run: |
          apt-get update
          apt-get install -y llvm-dev libclang-dev clang
          export LIBCLANG_PATH=/usr/local/lib
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Run cargo format
        run: |
          cargo fmt --all -- --check
      - name: Lint with clippy
        run: |
          cargo clippy -- -Dwarnings
      - name: Run cargo check
        run: |
          cargo check
      - name: Tests
        run: |
          cargo test -- --test-threads=1
